-- MySQL Script generated by MySQL Workbench
-- Mon May 20 21:38:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rentcar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rentcar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentcar` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rentcar` ;

-- -----------------------------------------------------
-- Table `rentcar`.`carbrand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentcar`.`carbrand` (
  `brandId` INT NOT NULL AUTO_INCREMENT,
  `brandName` VARCHAR(20) NOT NULL DEFAULT 'BRAK',
  PRIMARY KEY (`brandId`),
  UNIQUE INDEX `brandId_UNIQUE` (`brandId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentcar`.`carmodel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentcar`.`carmodel` (
  `modelId` INT NOT NULL AUTO_INCREMENT,
  `modelName` VARCHAR(30) NOT NULL,
  `brandId` INT NOT NULL,
  PRIMARY KEY (`modelId`),
  UNIQUE INDEX `modelId` (`modelId` ASC) VISIBLE,
  INDEX `fk_brandId` (`brandId` ASC) VISIBLE,
  CONSTRAINT `fk_brandId`
    FOREIGN KEY (`brandId`)
    REFERENCES `rentcar`.`carbrand` (`brandId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentcar`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentcar`.`car` (
  `carId` INT NOT NULL AUTO_INCREMENT,
  `brandId` INT NOT NULL,
  `modelId` INT NOT NULL,
  `carRegistration` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`carId`),
  UNIQUE INDEX `carId_UNIQUE` (`carId` ASC) VISIBLE,
  UNIQUE INDEX `carRegistration_UNIQUE` (`carRegistration` ASC) VISIBLE,
  INDEX `fk_carbrandId` (`brandId` ASC) VISIBLE,
  INDEX `fk_modelId` (`modelId` ASC) VISIBLE,
  CONSTRAINT `fk_carbrandId`
    FOREIGN KEY (`brandId`)
    REFERENCES `rentcar`.`carbrand` (`brandId`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_modelId`
    FOREIGN KEY (`modelId`)
    REFERENCES `rentcar`.`carmodel` (`modelId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rentcar`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentcar`.`reservation` (
  `reservationId` INT NOT NULL,
  `pickUpDateTime` DATETIME NOT NULL,
  `returnDateTime` DATETIME NOT NULL,
  `reservationCost` FLOAT NOT NULL,
  `carId` INT NOT NULL,
  PRIMARY KEY (`reservationId`),
  INDEX `fk_carId` (`carId` ASC) VISIBLE,
  CONSTRAINT `fk_carId`
    FOREIGN KEY (`carId`)
    REFERENCES `rentcar`.`car` (`carId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
